### ISSUE TITLE
Option to change RNG seed 

### ISSUE THREAD

**Issue by hvbish** [karllark/DIRTY_dustrt#29]
Currently the same random number generator seed is used each time DIRTY is run. It would be helpful if there was an option to request that a different seed be used, perhaps by adding a line to the parameter file.

This would be useful in the case when the results from multiple DIRTY runs are additive (for example, adding more photons to a star to increase S/N).

**Comment by karllark** [comment]
This capacity exists.  Just not in the docs.  Can be set in the Run section of the param file with the variable `random_num_seed`.  Expects a very large integer.  Default is `987654321`.
